### ISSUE TITLE
opam install node not working

### ISSUE THREAD

**Issue by enieber** [tmattio/ocaml-node#1]
This project sounds good, I am trying to compile by git clone because `opam install node` not work. Would be very nice if you publish this project in opam packages

**Comment by tmattio** [comment]
This project is just a prototype for now (I just pushed it yesterday), so I probably won't be releasing it in a while. If you want to use it regardless, you can always pin it: `opam pin node https://github.com/tmattio/ocaml-node.git`

**Comment by enieber** [comment]
thanks @tmattio
